# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: admin2
      POSTGRES_USER: admin2
      POSTGRES_DB: handyman

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080